fix issue of `this.value = 0`
JosephusPaye/Keen-UI pull request #516
Opened 2020-12-13 19:41 UTC by jeff-hykin

when the value is `0` (the number) it has a length of 1 char, but the `this.value ? this.value.length : 0` fails to pick that up

2021-02-10 09:29 UTC, JosephusPaye requested changes
Looks good, and just got one suggestion.

2021-02-10 09:29 UTC, JosephusPaye commented on src/UiTextbox.vue
> +            return (`${this.value}`).length;
```suggestion
            return this.value === null ? 0 : String(this.value).length;
```

2021-02-12 21:22 UTC, jeff-hykin commented
(gotta love JavaScript comparisions)

2021-12-31 03:38 UTC, JosephusPaye approved these changes

2021-12-31 03:40 UTC, merged

2021-12-31 03:40 UTC, JosephusPaye commented
Thanks!

2021-12-31 07:08 UTC, JosephusPaye commented
Released in [v1.3.2](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.3.2)