Hide overflow of a collapsible only during animation
JosephusPaye/Keen-UI pull request #519
Opened 2021-01-16 16:13 UTC by kilobyte2007

Sometimes we need to have elements that are out of the collapsible scope (we have a color picker in our case) and it is hidden by the collapsible. But because we only need overflow hidden while animating we can assign it to Vue's animation classes.

2021-01-26 05:18 UTC, JosephusPaye requested changes
Makes sense. Just a small change and we can merge...

2021-01-26 05:18 UTC, JosephusPaye commented on src/UiCollapsible.vue
> +    &.v-enter-active, &.v-leave-active {
```suggestion
    &.v-enter-active,
    &.v-leave-active {
```

2021-02-10 09:24 UTC, JosephusPaye approved these changes

2021-12-29 11:37 UTC, kilobyte2007 commented
Hey @JosephusPaye, can you please merge this? Thank you.

2021-12-31 03:07 UTC, merged

2021-12-31 07:11 UTC, JosephusPaye commented
Thanks! Released in [v1.3.2](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.3.2)