Allow tooltips for UiTab
JosephusPaye/Keen-UI pull request #539
Opened 2022-08-22 13:25 UTC by kilobyte2007

It is nice to have tooltips when the type of the tab is "icon".

2022-09-27 10:24 UTC, JosephusPaye commented
Looks good! However I wasn't able to test locally (was your fork is giving me a 404). Perhaps the close and reopen broke something?

2022-09-27 15:19 UTC, kilobyte2007 commented
Fixed now, please try again!

2022-10-11 07:12 UTC, JosephusPaye requested changes
One thing I noticed when testing locally...

2022-10-11 07:12 UTC, JosephusPaye commented on docs-src/pages/UiTabs.vue
> +                    </template>
In my local testing, I could only get this to work when changed to
```suggestion
                    <ui-icon slot="icon" :icon="tab.icon"></ui-icon>
```

2022-10-11 07:19 UTC, JosephusPaye commented on docs-src/pages/UiTabs.vue
> +                    </template>
Looks like your fork is still on Vue 2, that's why it wasn't working. It's fine when merged with `next` which has Vue 3.

2022-10-11 07:23 UTC, JosephusPaye approved these changes
LGTM

2022-10-11 07:23 UTC, merged