Added checks to make sure there are no unnecessary emits
JosephusPaye/Keen-UI pull request #544
Opened 2022-08-28 15:34 UTC by kilobyte2007

Some components were generating initial emits. It makes sense when the value is normalized, but sometimes it would just resend the initial value which is not really necessary. I have added some checks to prevent that.

Reason for this: For some components we have wrappers and it is really important to have consistency at the library level so that we know that events are only emitted when really needed.

Sorry for the amount of PRs lately. We've been using a branch with all these changes and I think it would be great to have them in the following release! Let me know what you think.

2022-09-27 10:34 UTC, JosephusPaye requested changes
Just a note, but we'll need to document this one in the release notes, since it's subtly changing the behavior of these components.

2022-09-27 10:34 UTC, JosephusPaye commented on src/UiSelect.vue
> +        if ((this.multiple && !Array.isArray(this.modelValue)) || (!this.modelValue && this.modelValue !== '')) {
Can we split this conditional into two variables? The multiple negations and `&&` is a bit tricky to follow 😅

2022-09-27 15:24 UTC, kilobyte2007 commented on src/UiSelect.vue
> +        if ((this.multiple && !Array.isArray(this.modelValue)) || (!this.modelValue && this.modelValue !== '')) {
Agreed! and fixed now!

2022-10-11 06:46 UTC, JosephusPaye approved these changes
LGTM, thanks!

2022-10-11 06:46 UTC, JosephusPaye commented on src/UiRadioGroup.vue
> +        selectedOptionValue: {
I like that the getter and setter here keep the read/write together, over the separate data + watcher we had before. 👍

2022-10-11 06:50 UTC, merged